"""Tally voucher + ledger flag sets used by the verbose XML emitter.

These are the ~120 IS*/VCH*/etc. flags that go on every voucher and the
13 ISDEEMEDPOSITIVE/etc. flags on every ledger entry, plus the dozens of
empty container lists Tally expects to round-trip its native export.

Only difference between Sales and Journal flag sets:
  * Sales: ISINVOICE=Yes
  * Journal: ISINVOICE=No

`VOUCHER_FLAGS` below is the Journal/Sales-shared shape. The two helpers
return the right variant.
"""
from __future__ import annotations

# ---- Voucher-level empty container lists (appear inside every <VOUCHER>) ----
# Order matches Tally's native export exactly. The only Sales/Journal difference
# is that Sales includes ALLINVENTORYENTRIES.LIST after GSTADVADJDETAILS.LIST.
VOUCHER_EMPTY_LISTS_SALES = [
    "EWAYBILLDETAILS.LIST", "EXCLUDEDTAXATIONS.LIST", "OLDAUDITENTRIES.LIST",
    "ACCOUNTAUDITENTRIES.LIST", "AUDITENTRIES.LIST", "DUTYHEADDETAILS.LIST",
    "GSTADVADJDETAILS.LIST", "ALLINVENTORYENTRIES.LIST", "CONTRITRANS.LIST",
    "EWAYBILLERRORLIST.LIST", "IRNERRORLIST.LIST", "HARYANAVAT.LIST",
    "SUPPLEMENTARYDUTYHEADDETAILS.LIST", "INVOICEDELNOTES.LIST",
    "INVOICEORDERLIST.LIST", "INVOICEINDENTLIST.LIST", "ATTENDANCEENTRIES.LIST",
    "ORIGINVOICEDETAILS.LIST", "INVOICEEXPORTLIST.LIST",
]
VOUCHER_EMPTY_LISTS_JOURNAL = [
    x for x in VOUCHER_EMPTY_LISTS_SALES if x != "ALLINVENTORYENTRIES.LIST"
]

VOUCHER_TRAILING_LISTS = [
    "GST.LIST", "STKJRNLADDLCOSTDETAILS.LIST", "GSTBUYERADDRESS.LIST",
    "GSTCONSIGNEEADDRESS.LIST", "PAYROLLMODEOFPAYMENT.LIST", "ATTDRECORDS.LIST",
    "GSTEWAYCONSIGNORADDRESS.LIST", "GSTEWAYCONSIGNEEADDRESS.LIST",
    "TEMPGSTRATEDETAILS.LIST", "TEMPGSTADVADJUSTED.LIST",
]

# ---- Ledger-entry-level empty container lists (inside every (ALL)LEDGERENTRIES.LIST) ----
LEDGER_EMPTY_LISTS = [
    "SERVICETAXDETAILS.LIST", "BANKALLOCATIONS.LIST", "BILLALLOCATIONS.LIST",
    "INTERESTCOLLECTION.LIST", "OLDAUDITENTRIES.LIST",
    "ACCOUNTAUDITENTRIES.LIST", "AUDITENTRIES.LIST", "INPUTCRALLOCS.LIST",
    "DUTYHEADDETAILS.LIST", "EXCISEDUTYHEADDETAILS.LIST", "RATEDETAILS.LIST",
    "SUMMARYALLOCS.LIST", "CENVATDUTYALLOCATIONS.LIST", "STPYMTDETAILS.LIST",
    "EXCISEPAYMENTALLOCATIONS.LIST", "TAXBILLALLOCATIONS.LIST",
    "TAXOBJECTALLOCATIONS.LIST", "TDSEXPENSEALLOCATIONS.LIST",
    "VATSTATUTORYDETAILS.LIST", "COSTTRACKALLOCATIONS.LIST",
    "REFVOUCHERDETAILS.LIST", "INVOICEWISEDETAILS.LIST", "VATITCDETAILS.LIST",
    "ADVANCETAXDETAILS.LIST", "TAXTYPEALLOCATIONS.LIST",
]

# ---- Voucher-level flag set (~120 boolean-like tags). ISINVOICE differs per type. ----
def _voucher_flags(is_invoice: str) -> list[tuple[str, str]]:
    return [
        ("DIFFACTUALQTY", "No"), ("ISMSTFROMSYNC", "No"), ("ISDELETED", "No"),
        ("ISSECURITYONWHENENTERED", "No"), ("ASORIGINAL", "No"), ("AUDITED", "No"),
        ("ISCOMMONPARTY", "No"), ("FORJOBCOSTING", "No"), ("ISOPTIONAL", "No"),
        ("USEFOREXCISE", "No"), ("ISFORJOBWORKIN", "No"),
        ("ALLOWCONSUMPTION", "No"), ("USEFORINTEREST", "No"),
        ("USEFORGAINLOSS", "No"), ("USEFORGODOWNTRANSFER", "No"),
        ("USEFORCOMPOUND", "No"), ("USEFORSERVICETAX", "No"),
        ("ISREVERSECHARGEAPPLICABLE", "No"), ("ISSYSTEM", "No"),
        ("ISFETCHEDONLY", "No"), ("ISGSTOVERRIDDEN", "No"),
        ("ISCANCELLED", "No"), ("ISONHOLD", "No"), ("ISSUMMARY", "No"),
        ("ISECOMMERCESUPPLY", "No"), ("ISBOENOTAPPLICABLE", "No"),
        ("ISGSTSECSEVENAPPLICABLE", "No"), ("IGNOREEINVVALIDATION", "No"),
        ("CMPGSTISOTHTERRITORYASSESSEE", "No"),
        ("PARTYGSTISOTHTERRITORYASSESSEE", "No"), ("IRNJSONEXPORTED", "No"),
        ("IRNCANCELLED", "No"), ("IGNOREGSTCONFLICTINMIG", "No"),
        ("ISOPBALTRANSACTION", "No"), ("IGNOREGSTFORMATVALIDATION", "No"),
        ("ISELIGIBLEFORITC", "Yes"), ("IGNOREGSTOPTIONALUNCERTAIN", "No"),
        ("UPDATESUMMARYVALUES", "No"), ("ISEWAYBILLAPPLICABLE", "No"),
        ("ISDELETEDRETAINED", "No"), ("ISNULL", "No"), ("ISEXCISEVOUCHER", "No"),
        ("EXCISETAXOVERRIDE", "No"), ("USEFORTAXUNITTRANSFER", "No"),
        ("ISEXER1NOPOVERWRITE", "No"), ("ISEXF2NOPOVERWRITE", "No"),
        ("ISEXER3NOPOVERWRITE", "No"), ("IGNOREPOSVALIDATION", "No"),
        ("EXCISEOPENING", "No"), ("USEFORFINALPRODUCTION", "No"),
        ("ISTDSOVERRIDDEN", "No"), ("ISTCSOVERRIDDEN", "No"),
        ("ISTDSTCSCASHVCH", "No"), ("INCLUDEADVPYMTVCH", "No"),
        ("ISSUBWORKSCONTRACT", "No"), ("ISVATOVERRIDDEN", "No"),
        ("IGNOREORIGVCHDATE", "No"), ("ISVATPAIDATCUSTOMS", "No"),
        ("ISDECLAREDTOCUSTOMS", "No"), ("VATADVANCEPAYMENT", "No"),
        ("VATADVPAY", "No"), ("ISCSTDELCAREDGOODSSALES", "No"),
        ("ISVATRESTAXINV", "No"), ("ISSERVICETAXOVERRIDDEN", "No"),
        ("ISISDVOUCHER", "No"), ("ISEXCISEOVERRIDDEN", "No"),
        ("ISEXCISESUPPLYVCH", "No"), ("GSTNOTEXPORTED", "No"),
        ("IGNOREGSTINVALIDATION", "No"), ("ISGSTREFUND", "No"),
        ("OVRDNEWAYBILLAPPLICABILITY", "No"), ("ISVATPRINCIPALACCOUNT", "No"),
        ("VCHSTATUSISVCHNUMUSED", "No"), ("VCHGSTSTATUSISINCLUDED", "No"),
        ("VCHGSTSTATUSISUNCERTAIN", "No"), ("VCHGSTSTATUSISEXCLUDED", "No"),
        ("VCHGSTSTATUSISAPPLICABLE", "No"),
        ("VCHGSTSTATUSISGSTR2BRECONCILED", "No"),
        ("VCHGSTSTATUSISGSTR2BONLYINPORTAL", "No"),
        ("VCHGSTSTATUSISGSTR2BONLYINBOOKS", "No"),
        ("VCHGSTSTATUSISGSTR2BMISMATCH", "No"),
        ("VCHGSTSTATUSISGSTR2BINDIFFPERIOD", "No"),
        ("VCHGSTSTATUSISRETEFFDATEOVERRDN", "No"),
        ("VCHGSTSTATUSISOVERRDN", "No"),
        ("VCHGSTSTATUSISSTATINDIFFDATE", "No"),
        ("VCHGSTSTATUSISRETINDIFFDATE", "No"),
        ("VCHGSTSTATUSMAINSECTIONEXCLUDED", "No"),
        ("VCHGSTSTATUSISBRANCHTRANSFEROUT", "No"),
        ("VCHGSTSTATUSISSYSTEMSUMMARY", "No"),
        ("VCHSTATUSISUNREGISTEREDRCM", "No"), ("VCHSTATUSISOPTIONAL", "No"),
        ("VCHSTATUSISCANCELLED", "No"), ("VCHSTATUSISDELETED", "No"),
        ("VCHSTATUSISOPENINGBALANCE", "No"), ("VCHSTATUSISFETCHEDONLY", "No"),
        ("VCHGSTSTATUSISOPTIONALUNCERTAIN", "No"),
        ("VCHSTATUSISREACCEPTFORHSNDONE", "No"),
        ("VCHSTATUSISREACCEPHSNSIXONEDONE", "No"),
        ("PAYMENTLINKHASMULTIREF", "No"), ("ISSHIPPINGWITHINSTATE", "No"),
        ("ISOVERSEASTOURISTTRANS", "No"), ("ISDESIGNATEDZONEPARTY", "No"),
        ("HASCASHFLOW", "No"), ("ISPOSTDATED", "No"),
        ("USETRACKINGNUMBER", "No"), ("ISINVOICE", is_invoice), ("MFGJOURNAL", "No"),
        ("HASDISCOUNTS", "No"), ("ASPAYSLIP", "No"), ("ISCOSTCENTRE", "No"),
        ("ISSTXNONREALIZEDVCH", "No"), ("ISEXCISEMANUFACTURERON", "No"),
        ("ISBLANKCHEQUE", "No"), ("ISVOID", "No"), ("ORDERLINESTATUS", "No"),
        ("VATISAGNSTCANCSALES", "No"), ("VATISPURCEXEMPTED", "No"),
        ("ISVATRESTAXINVOICE", "No"), ("VATISASSESABLECALCVCH", "No"),
        ("ISVATDUTYPAID", "Yes"), ("ISDELIVERYSAMEASCONSIGNEE", "No"),
        ("ISDISPATCHSAMEASCONSIGNOR", "No"), ("ISDELETEDVCHRETAINED", "No"),
        ("VCHONLYADDLINFOUPDATED", "No"), ("CHANGEVCHMODE", "No"),
        ("RESETIRNQRCODE", "No"),
    ]


VOUCHER_FLAGS_SALES = _voucher_flags("Yes")
VOUCHER_FLAGS_JOURNAL = _voucher_flags("No")

# ---- Ledger-entry flag sets ----
# Sign convention recap:
#   IDP=Yes + AMOUNT negative -> Dr
#   IDP=No  + AMOUNT positive -> Cr
# Voucher balances when sum(AMOUNT) across all entries == 0.

LEDGER_FLAGS_PARTY_DR = [  # party-ledger debit (e.g. Sundry Debtors Dr on Sales)
    ("ISDEEMEDPOSITIVE", "Yes"), ("LEDGERFROMITEM", "No"),
    ("REMOVEZEROENTRIES", "No"), ("ISPARTYLEDGER", "Yes"),
    ("GSTOVERRIDDEN", "No"), ("ISGSTASSESSABLEVALUEOVERRIDDEN", "No"),
    ("STRDISGSTAPPLICABLE", "No"), ("STRDGSTISPARTYLEDGER", "No"),
    ("STRDGSTISDUTYLEDGER", "No"), ("CONTENTNEGISPOS", "No"),
    ("ISLASTDEEMEDPOSITIVE", "Yes"), ("ISCAPVATTAXALTERED", "No"),
    ("ISCAPVATNOTCLAIMED", "No"),
]

LEDGER_FLAGS_INCOME_CR = [  # non-party ledger on credit side (Sale / CGST / SGST Cr)
    ("ISDEEMEDPOSITIVE", "No"), ("LEDGERFROMITEM", "No"),
    ("REMOVEZEROENTRIES", "No"), ("ISPARTYLEDGER", "No"),
    ("GSTOVERRIDDEN", "No"), ("ISGSTASSESSABLEVALUEOVERRIDDEN", "No"),
    ("STRDISGSTAPPLICABLE", "No"), ("STRDGSTISPARTYLEDGER", "No"),
    ("STRDGSTISDUTYLEDGER", "No"), ("CONTENTNEGISPOS", "No"),
    ("ISLASTDEEMEDPOSITIVE", "No"), ("ISCAPVATTAXALTERED", "No"),
    ("ISCAPVATNOTCLAIMED", "No"),
]

LEDGER_FLAGS_PARTY_CR = [  # party-ledger credit (e.g. Sundry Debtors Cr on Journal)
    ("ISDEEMEDPOSITIVE", "No"), ("LEDGERFROMITEM", "No"),
    ("REMOVEZEROENTRIES", "No"), ("ISPARTYLEDGER", "Yes"),
    ("GSTOVERRIDDEN", "No"), ("ISGSTASSESSABLEVALUEOVERRIDDEN", "No"),
    ("STRDISGSTAPPLICABLE", "No"), ("STRDGSTISPARTYLEDGER", "No"),
    ("STRDGSTISDUTYLEDGER", "No"), ("CONTENTNEGISPOS", "No"),
    ("ISLASTDEEMEDPOSITIVE", "No"), ("ISCAPVATTAXALTERED", "No"),
    ("ISCAPVATNOTCLAIMED", "No"),
]


def round_off_flags(dr: bool) -> list[tuple[str, str]]:
    """ROUND OFF entry flags. dr=True means we lost (Dr); dr=False means we gained (Cr)."""
    base = list(LEDGER_FLAGS_PARTY_DR if dr else LEDGER_FLAGS_INCOME_CR)
    # ROUND OFF is never a party ledger.
    return [(k, "No" if k == "ISPARTYLEDGER" else v) for k, v in base]
